[[GCC]]
arch = "x86_64"
git-tree-sha1 = "d335c2f6df55e88466ed0317080614cd8f80c74d"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC.download]]
    sha256 = "579c56fb78289432daf08ca905b7161620449a048faebb0445ae71a3c6a42b3d"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.0-GXXTEST/GCC-v9.1.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC-build_log]]
arch = "x86_64"
git-tree-sha1 = "3227f3babe9a13651e971bc428d1ecc66b773e31"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-build_log.download]]
    sha256 = "127ab08d81bea167267992d5c06ed42e1e0428c81858c92e8d71bc9aac7d3ea8"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.0-GXXTEST/GCC-build_log-v9.1.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC-extract_log]]
arch = "x86_64"
git-tree-sha1 = "de47d441ce5b2e2dada29fd28179c3b595fa63b7"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-extract_log.download]]
    sha256 = "0f728686e3887792c3e2c461e9510b7240c702ca1092b542eb1d0671774818b4"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.0-GXXTEST/GCC-extract_log-v9.1.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
