[[GCC]]
arch = "aarch64"
git-tree-sha1 = "3aa5b9089b9f3dfea25316d5fcceaaa7da203ce9"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC.download]]
    sha256 = "e8fa710c4741277663ea061be36af0307a4e3c0cc32f10532178a30bd087892b"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.0-GCC/GCC-v9.1.0-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC]]
arch = "x86_64"
git-tree-sha1 = "0c21ba463c0a9d6bb2aea00b9db7437f2f3da56a"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC.download]]
    sha256 = "129e12212a0ffc2abe1f5dd90078fef6777e6a64583fb00b0274647f8fddf216"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.0-GCC/GCC-v9.1.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC-build_log]]
arch = "aarch64"
git-tree-sha1 = "60b152d12d84df566301dc9cce7bf473fde03254"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-build_log.download]]
    sha256 = "924fc636dc58d4862ffeefa60050b1117fe831c7dae0f4fe60eb11e5513f376d"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.0-GCC/GCC-build_log-v9.1.0-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC-build_log]]
arch = "x86_64"
git-tree-sha1 = "3832fa2e7c9f18b441e4516282468f8265a62a31"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-build_log.download]]
    sha256 = "60d7c86e1b6d244d62571aa6f163e917334382c93496065240cb99a0269ffc8d"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.0-GCC/GCC-build_log-v9.1.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC-extract_log]]
arch = "aarch64"
git-tree-sha1 = "aef8e95e08528c212134070c22038ac1a9a80f4b"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-extract_log.download]]
    sha256 = "8c34fa918d19c8dec84eeaa50da5610d6e0b4c915c3f5d44170fcdda0ab9a4a3"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.0-GCC/GCC-extract_log-v9.1.0-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e71d0dec3cc26e9e99b0c7f54eceb884df0e414f"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-extract_log.download]]
    sha256 = "48d039c2ab3570c29adc3353024edb224a86c3f5e8e78dfce9507b6d8e588bb3"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.0-GCC/GCC-extract_log-v9.1.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
