[[GCC]]
arch = "x86_64"
git-tree-sha1 = "b6b8448675bdc745ed57e15554f7d4ca0197fcbf"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCC.download]]
    sha256 = "3a1ebcd84cb4a7be6d4ec76fdf9ce7dcb250f83983eaeacea383d0c99b958971"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v14.2.0/GCC-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCC]]
arch = "x86_64"
git-tree-sha1 = "3af9eb58d3413a3dbcf343a8d6131b81915c16ff"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCC.download]]
    sha256 = "eecc428d59aaeb18a1c3eb31b5ed728d630dce6db2c5b093f17588a2a00b8d92"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v14.2.0/GCC-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"

[[GCC-build_log]]
arch = "x86_64"
git-tree-sha1 = "08184663c064d7c03ed2a894bb52692e81a0bb52"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCC-build_log.download]]
    sha256 = "394b54bb01a98712c73523166b15c9683d8a3f17adb8a9e02ae0877fede1768b"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v14.2.0/GCC-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCC-build_log]]
arch = "x86_64"
git-tree-sha1 = "7533848b2086adc3cbdcd5de9bf4a76da55f7337"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCC-build_log.download]]
    sha256 = "decdf7cd910d404eba0cf13137f6df85f91bf030c1587fa48f00e83d8430b725"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v14.2.0/GCC-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"

[[GCC-extract_log]]
arch = "x86_64"
git-tree-sha1 = "9ebfea728e4f88beecd11283b23b13d978507ba4"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCC-extract_log.download]]
    sha256 = "665af4efbc8aa8e99ec8c978285f9740aebd24cdfa6371d1a131874436ffeeb2"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v14.2.0/GCC-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCC-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1c6caf5b1877f97d517349b5a1b458e2c9078b4a"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCC-extract_log.download]]
    sha256 = "b92ab2ca716de97b63874b3f513b66801f5b1bc0388709d74bb9a3aaebcf4266"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v14.2.0/GCC-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
