[[GCC]]
arch = "aarch64"
git-tree-sha1 = "3aa5b9089b9f3dfea25316d5fcceaaa7da203ce9"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC.download]]
    sha256 = "b0cd2624a030be64b71c9802676dc8b4181b2e2dbb3c4202a44fc6b056e4e84d"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.1-GCC/GCC-v9.1.1-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC]]
arch = "x86_64"
git-tree-sha1 = "0c21ba463c0a9d6bb2aea00b9db7437f2f3da56a"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC.download]]
    sha256 = "b89c739a34a095ac993ccb20eb8a7c3b9d1b59f5dbdf2080eced1e8996e7ada3"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.1-GCC/GCC-v9.1.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC-build_log]]
arch = "aarch64"
git-tree-sha1 = "9eb591cb0e5b7c31edd6acef873f54d3f9d50df6"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-build_log.download]]
    sha256 = "4829ee03964737192394b1e98f5efedfbb1b225a91233b4726e053802dc2a9d4"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.1-GCC/GCC-build_log-v9.1.1-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC-build_log]]
arch = "x86_64"
git-tree-sha1 = "381d839a27b773b4de28751bf0f5f48a3564c7ae"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-build_log.download]]
    sha256 = "ea63e961d297366abfcaa4363f4245ba06c82045e3b64d6da88e966289a013fd"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.1-GCC/GCC-build_log-v9.1.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC-extract_log]]
arch = "aarch64"
git-tree-sha1 = "89c930e048085ca05178c94923b345bc7c54ee48"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-extract_log.download]]
    sha256 = "63a12861c58795e1e9edc856a29de6a49fb7267ee6f8919472ebc5612bec3f47"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.1-GCC/GCC-extract_log-v9.1.1-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ddac15329b6b2bc87d806f4e230fff36dccd92d8"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC-extract_log.download]]
    sha256 = "b249d66629a5795c76fdb20d820447dd63307a8ab607c237b8dd0b5fa52da5cb"
    url = "https://github.com/staticfloat/GCC_jll.jl/releases/download/v9.1.1-GCC/GCC-extract_log-v9.1.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
